# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d9ba76adc17a5256c10c057e1ba79a91086b7595f69bc0623749c64fb8ce7ef6817e9432ccc364f15705cc94b3f71ece3ed05beeca5c6f017b0db7a580d1ad1

test:
  secret_key_base: b94e307f6f58763d7138a93d61bda70b6b56e8b046c342b6661e7bce3e8ffa0501ff9b721b7eb9eef3d18f4564f69692b95800e77afb9e2f6d16218789f8ee28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
